### ISSUE TITLE
I get This Error

### ISSUE THREAD

**Issue by presider** [graniet/operative-framework#4]
when ı use whois_domain modules type show options or run or etc. ı get this error...

Traceback (most recent call last):
  File "operative.py", line 8, in <module>
    operative.user_put()
  File "/root/Desktop/Github/operative-framework/core/operative.py", line 53, in user_put
    mecanic.load(user_input)
  File "/root/Desktop/Github/operative-framework/core/mecanic.py", line 19, in load
    load_module(name)
  File "/root/Desktop/Github/operative-framework/core/mecanic.py", line 83, in load_module
    use_module(module)
  File "/root/Desktop/Github/operative-framework/core/mecanic.py", line 52, in use_module
    mod = __import__(module_path, fromlist=['module_element'])
  File "/root/Desktop/Github/operative-framework/core/modules/whois_domain.py", line 8, in <module>
    import pythonwhois
ImportError: No module named pythonwhois

**Comment by graniet** [comment]
Hello,

Please install pythonwhois (python-whois) module.
https://pypi.python.org/pypi/pythonwhois

Thanks you.
